CONTAINER Oremotecontrolboard
{
	NAME Oremotecontrolboard;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		STRING BODY_PART { }
		BUTTON CONNECT_BUTTON { NAME CONNECT_TEXT; }
		BUTTON DISCONNECT_BUTTON { NAME DISCONNECT_TEXT; }
	}
}
