#ifndef OREMOTECONTROLBOARD_H__
#define OREMOTECONTROLBOARD_H__

enum
{
	BODY_PART = 10000,
	ID_GROUP_CONTROL,
	CONNECT_BUTTON,
	DISCONNECT_BUTTON,
	CONFIGURE_BUTTON,
	SENDPOS_BUTTON,
	ID_GROUP_CONTROL_MODE,
	CONTROL_MODE =2000,
		CONTROL_MODE_POSITION = 0,
		CONTROL_MODE_POSITION_DIRECT = 1,
	JOINT_COUNT,
	JOINTS
};

#endif
