CONTAINER Oremotecontrolboard
{
	NAME Oremotecontrolboard;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		STRING BODY_PART { }
		BUTTON CONNECT_BUTTON { NAME CONNECT_TEXT; }
		BUTTON DISCONNECT_BUTTON { NAME DISCONNECT_TEXT; }
		BUTTON CONFIGURE_BUTTON { NAME CONFIGURE_TEXT; }
		LONG JOINT_COUNT	{ MIN 0; MAX 50; }
	}
}
